import assert from 'node:assert/strict';import {test} from 'node:test';
import {processPush,pushFailure} from '../../src/modules/notifications/push.ts';
import {validPushSubscription,safeAdminReturn,bookingTarget} from '../../src/modules/notifications/contracts.ts';
import {invokeAdminNotifications} from '../../netlify/functions/admin-notifications-schedule.mjs';
import {readFile} from 'node:fs/promises';
import {runInNewContext} from 'node:vm';
const op='10000000-0000-4000-8000-000000000001',booking='10000000-0000-4000-8000-000000000002';
const subscription={endpoint:'https://fcm.googleapis.com/fcm/send/test',keys:{p256dh:'B'.repeat(87),auth:'A'.repeat(22)}};
test('subscriptions reject request-proxy URLs, bad keys and credentials',()=>{assert.equal(validPushSubscription(subscription),true);for(const endpoint of ['http://fcm.googleapis.com/x','https://localhost/x','https://127.0.0.1','https://fcm.googleapis.com.evil.test/x','https://user@fcm.googleapis.com/x','https://fcm.googleapis.com:8443/x'])assert.equal(validPushSubscription({...subscription,endpoint}),false);assert.equal(validPushSubscription({...subscription,keys:{auth:'bad',p256dh:'bad'}}),false);});
test('push payload targets exact booking and multiple devices independently',async()=>{const jobs=[1,2].map(id=>({id:String(id),operator_id:op,subscription_id:String(id),notification_id:'n',lease_token:'token'}));const results=[],sent=[];const store={claim:async()=>jobs.shift()??null,read:async()=>({subscription:{endpoint:subscription.endpoint,...subscription.keys},notification:{id:'n',title:'New booking',message:'3 guests',booking_id:booking}}),finish:async(j,r)=>results.push([j.id,r])};assert.equal(await processPush(store,async(s,p)=>sent.push(JSON.parse(p))),2);assert.deepEqual(results,[['1','accepted'],['2','accepted']]);assert.equal(sent[0].url,bookingTarget(op,booking));assert.equal(sent[0].tag,sent[1].tag);});
test('network ambiguity never retries; permanent expiry and temporary rejection classified',()=>{assert.equal(pushFailure(Error()).result,'uncertain');assert.equal(pushFailure({statusCode:410}).result,'expired');assert.equal(pushFailure({statusCode:404}).result,'expired');assert.equal(pushFailure({statusCode:429}).result,'retry');assert.equal(pushFailure({statusCode:503}).result,'retry');assert.equal(pushFailure({statusCode:403}).result,'failed');});
test('revoked device is skipped without invoking provider; provider failure is recorded',async()=>{let job={id:'j',operator_id:op,lease_token:'t'},sent=0,result;const store={claim:async()=>{const j=job;job=null;return j;},read:async()=>null,finish:async(j,r)=>{result=r;}};await processPush(store,async()=>{sent++;});assert.equal(sent,0);assert.equal(result,'skipped');job={id:'j',operator_id:op};store.read=async()=>({subscription:{endpoint:subscription.endpoint,...subscription.keys},notification:{id:'n',title:'New booking',message:'3 guests',booking_id:booking}});await processPush(store,async()=>{throw {statusCode:410};});assert.equal(result,'expired');});
test('login return destination is allowlisted and retains booking context',()=>{const target=bookingTarget(op,booking);assert.equal(safeAdminReturn(target),target);for(const value of ['https://evil.test','//evil.test','/admin/../public','/admin?next=https://evil.test',target+'&next=evil'])assert.equal(safeAdminReturn(value),'/admin');});
test('scheduler never sends from previews or when disabled and uses fixed matching site origin',async()=>{let sent=0;const transport=async()=>{sent++;return {ok:true,json:async()=>({status:'push'})};};assert.deepEqual(await invokeAdminNotifications({deploy:{context:'deploy-preview',published:false}},{},transport),{status:'disabled'});assert.equal(sent,0);const context={deploy:{context:'production',published:true},site:{url:'https://example.test'}};const env={APP_ENV:'production',ADMIN_NOTIFICATIONS_ENABLED:'true',CRON_SECRET:'a'.repeat(32),NEXT_PUBLIC_SITE_URL:'https://example.test'};await invokeAdminNotifications(context,env,transport);assert.equal(sent,1);await assert.rejects(invokeAdminNotifications(context,{...env,NEXT_PUBLIC_SITE_URL:'https://other.test'},transport));});

test('service worker displays push, focuses exact booking and safely handles malformed payloads without caching',async()=>{
 const handlers={},shown=[],opened=[],focused=[];let pending;
 const self={addEventListener:(name,fn)=>{handlers[name]=fn;},location:{origin:'https://example.test'},registration:{showNotification:async(title,options)=>shown.push({title,options})},clients:{matchAll:async()=>[{url:'https://example.test/admin',navigate:async url=>opened.push(url),focus:async()=>focused.push(true)}],openWindow:async url=>opened.push(url)}};
 runInNewContext(await readFile(new URL('../../public/admin/sw.js',import.meta.url),'utf8'),{self,URL});
 assert.deepEqual(Object.keys(handlers).sort(),['notificationclick','push']);
 const path=bookingTarget(op,booking);handlers.push({data:{json:()=>({body:'New booking',tag:'event-one',url:path})},waitUntil:p=>{pending=p;}});await pending;
 assert.equal(shown[0].options.data.url,path);assert.equal(shown[0].options.tag,'event-one');
 let closed=false;handlers.notificationclick({notification:{data:shown[0].options.data,close:()=>{closed=true;}},waitUntil:p=>{pending=p;}});await pending;
 assert.equal(opened[0],'https://example.test'+path);assert.equal(focused.length,1);assert.equal(closed,true);
 handlers.push({data:{json:()=>{throw Error('bad');}},waitUntil:p=>{pending=p;}});await pending;assert.equal(shown[1].options.data.url,'/admin');
 handlers.push({data:{json:()=>({body:'x'.repeat(1000),url:'https://evil.test'})},waitUntil:p=>{pending=p;}});await pending;assert.equal(shown[2].options.data.url,'/admin');assert.equal(shown[2].options.body.length,500);
});
