'use client';
import {useCallback,useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {NotificationBell,NotificationCenter,NotificationContext} from '@/app/admin/notifications';
import {notificationTypes,type InboxItem,type Preference} from '@/modules/notifications/contracts';
import styles from '@/app/admin/admin.module.css';
const operator='10000000-0000-4000-8000-000000000001';
const initial:InboxItem[]=Array.from({length:4},(_,i)=>({id:`10000000-0000-4000-8000-00000000001${i}`,notification_id:`notification-${i}`,read_at:i===3?'2030-01-01T12:00:00Z':null,created_at:'2030-01-01T12:00:00Z',notification:{id:`notification-${i}`,type:notificationTypes[i],title:['New booking','Booking modified','Booking cancelled','Guest checked in'][i],message:'Booking DEMO-1001 - 4 guests / 3 seats - 2030-01-02 13:00 - EUR 25.00. Details at processing time.',booking_id:'10000000-0000-4000-8000-000000000050',severity:'info',event_at:'2030-01-01T12:00:00Z'}}));
/** Synthetic layout/interaction fixture, never a substitute for a live Realtime/push test. */
export function NotificationFixture(){
 const [items,setItems]=useState(initial),[version,setVersion]=useState(0),[preferences,setPreferences]=useState<Preference[]>(notificationTypes.map(type=>({type,in_app:true,push:true})));
 const request=useCallback(async(query='')=>{if(query.includes('settings=1'))return {devices:[],preferences,publicKey:'',workerEnabled:false};const filter=new URLSearchParams(query).get('filter');return {items:items.filter(i=>!filter||filter==='all'||filter==='unread'&&!i.read_at||filter===i.notification.type||filter==='system'&&['email_delivery_failed','payment_status_changed','booking_status_changed'].includes(i.notification.type)),unread:items.filter(x=>!x.read_at).length,next:null};},[items,preferences]);
 const mutate=async(action:unknown)=>{const a=action as {kind:string;id:string;read:boolean;type:Preference['type'];in_app:boolean;push:boolean};if(a.kind==='read')setItems(old=>old.map(i=>a.id==='all'||i.id===a.id?{...i,read_at:a.read?new Date().toISOString():null}:i));if(a.kind==='preference')setPreferences(old=>old.map(p=>p.type===a.type?{type:a.type,in_app:a.in_app,push:a.push}:p));setVersion(v=>v+1);return {ok:true};};
 return <NotificationContext.Provider value={{operator,inbox:{items,unread:items.filter(x=>!x.read_at).length,next:null},error:'',connection:'Synthetic fixture',version,refresh:async()=>setVersion(v=>v+1),mutate,request}}><main className={styles.shell}><p>Development fixture: synthetic data, no live subscriptions or push.</p><header className={styles.header}><div className={styles.headerIdentity}><Image src="/brand/logo-light.svg" alt="Sightseeing Shkodra" width={170} height={51}/><div className={styles.workspaceIdentity}><strong>Demo workspace</strong><span>Owner</span></div></div><div className={styles.headerActions}><NotificationBell/><Link className={styles.websiteLink} href="/">View website</Link><Link className={styles.workspaceSwitch} href="/admin">Switch workspace</Link><button>Sign out</button></div></header><div className={styles.workspace}><nav className={styles.nav}>Notifications</nav><div className={styles.panel}><h1>Notifications</h1><button onClick={()=>{const id=crypto.randomUUID();setItems(old=>[{...initial[0],id,notification_id:id,created_at:new Date().toISOString(),notification:{...initial[0].notification,id,event_at:new Date().toISOString()}},...old]);setVersion(v=>v+1);}}>Simulate incoming alert</button><NotificationCenter/></div></div></main></NotificationContext.Provider>;
}
