import assert from 'node:assert/strict';import {before,after,test} from 'node:test';import {createTestDatabase,loadDevelopmentFixtures} from '../helpers/database.mjs';
let db,actor,product,schedule,dep,hold;const op='10000000-0000-4000-8000-000000000001',counts={adult:2,child:2,infant:1},session='calendar-test-session-1234567890123456789';
const config={adult:{min:13,max:null,price:1000},child:{min:3,max:12,price:500},infant:{min:0,max:2,price:0}};
async function stamp(table,id){return (await db.query(`select updated_at::text as stamp from ${table} where id=$1`,[id])).rows[0].stamp;}
async function override(from,to,value,confirm=false){return db.query('select save_calendar_override_v1($1,$2,$3,$4,$5,$6,$7,$8,$9)',[op,actor,schedule,from,to,[1,2,3,4,5,6,7],JSON.stringify(value),confirm,await stamp('service_schedules',schedule)]);}
before(async()=>{db=await createTestDatabase({now:'2026-09-23T00:00:00Z'});await loadDevelopmentFixtures(db);const u=(await db.query('insert into auth.users values(gen_random_uuid()) returning id')).rows[0].id;actor=(await db.query("insert into staff_profiles(operator_id,auth_user_id,role) values($1,$2,'owner') returning id",[op,u])).rows[0].id;product=(await db.query(`insert into products(operator_id,type,title,slug,status,pricing_rules,capacity_rules) values($1,'van_tour','Calendar test','calendar-test','published','{"version":1,"model":"per_guest","currency":"EUR","unit_price":1000}','{"version":1,"model":"departure_seats"}') returning id`,[op])).rows[0].id;schedule=(await db.query("select save_service_schedule_v1($1,$2,$3,'2026-09-24','2026-10-31',$4,$5,8,null,'active') id",[op,actor,product,[1,2,3,4,5,6,7],JSON.stringify([{time:'09:00'},{time:'15:00'}])])).rows[0].id;});after(async()=>db?.close());
test('validates ages, requires manual category prices, accepts zero price',async()=>{await assert.rejects(db.query('select passenger_quote_v1($1,$2,$3,$4)',[product,'2026-10-07','15:00',JSON.stringify(counts)]),/not been configured/);await db.query('select save_passenger_pricing_v1($1,$2,$3,$4,$5)',[op,actor,product,JSON.stringify(config),await stamp('products',product)]);await assert.rejects(db.query('select save_passenger_pricing_v1($1,$2,$3,$4,$5)',[op,actor,product,JSON.stringify({...config,child:{...config.child,min:2}}),await stamp('products',product)]),/overlap/);});
test('range then departure prices override independently; zero infants consume seats',async()=>{await override('2026-10-01','2026-10-15',{prices:{adult:800,child:400},capacity:7});await override('2026-10-07','2026-10-07',{times:[{time:'09:00'},{time:'15:00'}],departures:{'15:00':{prices:{adult:700},capacity:6}}});const a=(await db.query('select read_passenger_availability_v1($1,$2,$3,$4) a',[op,product,'2026-10-07',JSON.stringify(counts)])).rows[0].a;dep=a.departures.find(d=>d.start_time==='15:00:00');assert.equal(dep.capacity,6);assert.equal(dep.passenger_quote.total,2200);assert.deepEqual(dep.passenger_quote.lines.map(l=>l.unitPrice),[700,400,0]);hold=(await db.query('select * from create_passenger_hold_v1($1,$2,$3,gen_random_uuid(),5,$4)',[op,dep.id,session,JSON.stringify(counts)])).rows[0];assert.equal(hold.quantity,5);});
test('adult rule rejects hold bypass and passenger changes; booking snapshot remains immutable',async()=>{await assert.rejects(db.query('select create_passenger_hold_v1($1,$2,$3,gen_random_uuid(),1,$4)',[op,dep.id,session,JSON.stringify({adult:0,child:1,infant:0})]),/adult is required/);const order=(await db.query("select create_meeting_point_booking_v1($1,$2,$3,'Test Customer','calendar@example.test',null) o",[op,hold.id,session])).rows[0].o;assert.equal(order.total,2200);assert.equal(order.status,'confirmed');await assert.rejects(db.query('update booking_items set quantity=1 where order_id=$1',[order.orderId]),/immutable/);await override('2026-10-01','2026-10-15',{prices:{adult:900,child:600}});assert.equal((await db.query('select total from orders where id=$1',[order.orderId])).rows[0].total,2200);});
test('booked closure requires confirmation and never cancels bookings; capacity cannot undercut seats',async()=>{await assert.rejects(override('2026-10-07','2026-10-07',{closed:true}),/Confirm closure/);await assert.rejects(override('2026-10-07','2026-10-07',{times:[{time:'15:00'}],capacity:4}),/Capacity cannot/);await override('2026-10-07','2026-10-07',{closed:true},true);assert.equal((await db.query('select count(*)::int n from booking_items where departure_id=$1 and status=\'confirmed\'',[dep.id])).rows[0].n,1);await assert.rejects(db.query('select create_passenger_hold_v1($1,$2,$3,gen_random_uuid(),1,$4)',[op,dep.id,session,JSON.stringify({adult:1,child:0,infant:0})]),/unavailable/);});

test('monthly projection is bounded and reads effective rules without generating inventory',async()=>{const before=(await db.query('select count(*)::int n from departures where product_id=$1',[product])).rows[0].n;const calendar=(await db.query('select read_operations_calendar_v1($1,$2,$3,$4) c',[op,actor,schedule,'2026-10-01'])).rows[0].c;assert.equal(calendar.days.length,31);assert.equal(calendar.days.find(d=>d.date==='2026-10-07').slots.find(s=>s.time==='15:00').booked,5);assert.equal((await db.query('select count(*)::int n from departures where product_id=$1',[product])).rows[0].n,before);});
test('offer calculation applies only to selected categories and keeps free prices',async()=>{await override('2026-10-08','2026-10-08',{offer:{name:'Test offer',label:'Local test',type:'percent',values:{adult:20},times:['15:00']}});const q=(await db.query('select passenger_quote_v1($1,$2,$3,$4) q',[product,'2026-10-08','15:00',JSON.stringify(counts)])).rows[0].q;assert.deepEqual(q.lines.map(l=>l.unitPrice),[720,600,0]);assert.equal(q.lines[0].offer.name,'Test offer');const morning=(await db.query('select passenger_quote_v1($1,$2,$3,$4) q',[product,'2026-10-08','09:00',JSON.stringify(counts)])).rows[0].q;assert.equal(morning.lines[0].unitPrice,900);});
