import assert from 'node:assert/strict';import {before,after,test} from 'node:test';import {randomUUID} from 'node:crypto';
import {createTestDatabase,loadDevelopmentFixtures,setTestClock} from '../helpers/database.mjs';import {quoteAvailability} from '../../src/modules/booking/availability.ts';
let db,product;const op='10000000-0000-4000-8000-000000000001',session='customer-management-test-session-123456789';
before(async()=>{db=await createTestDatabase({now:'2030-06-01T06:00:00Z'});await loadDevelopmentFixtures(db);product=(await db.query(`insert into products(operator_id,type,title,slug,status,pricing_rules,capacity_rules,passenger_pricing) values($1,'van_tour','Management test',gen_random_uuid()::text,'published','{"version":1,"model":"per_guest","currency":"EUR","unit_price":1000}','{"version":1,"model":"departure_seats"}','{"adult":{"min":13,"max":null,"price":1000},"child":{"min":3,"max":12,"price":500},"infant":{"min":0,"max":2,"price":0}}') returning id`,[op])).rows[0].id;});after(async()=>db?.close());
async function departure(time='13:00',date='2030-06-01'){return(await db.query("insert into departures(operator_id,product_id,service_date,start_time,capacity,status) values($1,$2,$3,$4,8,'scheduled') returning id",[op,product,date,time])).rows[0].id;}
async function book(dep,counts){const qty=Object.values(counts).reduce((a,b)=>a+b,0);const h=(await db.query('select * from create_passenger_hold_v1($1,$2,$3,$4,$5,$6)',[op,dep,session,randomUUID(),qty,counts])).rows[0];return(await db.query("select create_meeting_point_booking_v1($1,$2,$3,'Customer','test@example.test') b",[op,h.id,session])).rows[0].b;}
async function modify(b,dep,counts,version=0,request=randomUUID()){return (await db.query('select modify_customer_booking_v1($1,$2,$3,$4,$5,$6) b',[b.managementToken,version,dep,counts,counts.adult*1000+counts.child*500,request])).rows[0].b;}
async function read(b){return(await db.query('select customer_booking_v1($1) b',[b.managementToken])).rows[0].b;}
test('8 adults and 2 infants use 8 seats; price/people preserved; stale ninth seat rejected',async()=>{const dep=await departure();const b=await book(dep,{adult:8,child:0,infant:2});assert.equal((await read(b)).occupiedSeats,8);assert.equal(b.items[0].quantity,10);await assert.rejects(book(dep,{adult:1,child:0,infant:0}),/capacity/);await db.query('select cancel_customer_booking_v1($1)',[b.managementToken]);assert.equal((await read(b)).status,'cancelled');await book(dep,{adult:8,child:0,infant:0});});
test('same departure excludes own seats; rejected increase leaves original allocation and total intact; reductions release seats',async()=>{const dep=await departure('13:01');const b=await book(dep,{adult:3,child:0,infant:0});await book(dep,{adult:4,child:0,infant:0});const request=randomUUID();assert.equal((await modify(b,dep,{adult:4,child:0,infant:2},0,request)).occupiedSeats,4);assert.equal((await modify(b,dep,{adult:4,child:0,infant:2},0,request)).version,1);await assert.rejects(modify(b,dep,{adult:5,child:0,infant:0},1),/capacity/);assert.equal((await read(b)).occupiedSeats,4);await modify(b,dep,{adult:2,child:0,infant:0},1);await book(dep,{adult:2,child:0,infant:0});});
test('atomic departure change rejects full target without releasing original; emits one modification event',async()=>{const a=await departure('13:02'),z=await departure('15:02');const b=await book(a,{adult:4,child:0,infant:0});const full=await book(z,{adult:8,child:0,infant:0});await assert.rejects(modify(b,z,{adult:4,child:0,infant:0}),/capacity/);assert.equal((await read(b)).departureId,a);await db.query('select cancel_customer_booking_v1($1)',[full.managementToken]);await modify(b,z,{adult:4,child:0,infant:0});assert.equal((await read(b)).departureId,z);assert.equal((await db.query("select count(*)::int n from domain_events where event_type='booking.modified' and payload->>'orderId'=$1",[b.orderId])).rows[0].n,1);});
test('invalid token, no adult, stale version, price changes and paid modifications fail safely',async()=>{const dep=await departure('13:03');const b=await book(dep,{adult:2,child:0,infant:0});await assert.rejects(db.query('select customer_booking_v1($1)',['0'.repeat(64)]),/unavailable/);await assert.rejects(modify(b,dep,{adult:0,child:2,infant:0}),/adult/);await assert.rejects(modify(b,dep,{adult:2,child:0,infant:0},99),/changed/);await assert.rejects(db.query('select modify_customer_booking_v1($1,0,$2,$3,1,$4)',[b.managementToken,dep,{adult:2,child:0,infant:0},randomUUID()]),/Price changed/);assert.equal((await read(b)).version,0);await db.query("insert into payments(operator_id,order_id,provider,provider_ref,amount,currency) values($1,$2,'meeting_point','test',2000,'EUR')",[op,b.orderId]);await assert.rejects(modify(b,dep,{adult:2,child:0,infant:0}),/operator/);await assert.rejects(db.query('select cancel_customer_booking_v1($1)',[b.managementToken]),/operator/);});
test('15-minute exact cutoff: hold/confirmation, current modification/cancellation and target all authoritative',async()=>{
 for(const second of [-1,0,1]){
  await setTestClock(db,'2030-06-02T06:00:00Z');const dep=await departure('13:00','2030-06-02'),target=await departure('15:00','2030-06-02');const b=await book(dep,{adult:1,child:0,infant:0});const c=await book(dep,{adult:1,child:0,infant:0});
  const hold=(await db.query('select * from create_hold_v1($1,$2,$3,$4,1)',[op,dep,session,randomUUID()])).rows[0];
  await setTestClock(db,new Date(Date.parse('2030-06-02T10:45:00Z')+second*1000).toISOString());
  if(second<0){await modify(b,target,{adult:1,child:0,infant:0});await db.query('select cancel_customer_booking_v1($1)',[c.managementToken]);}
  else {await assert.rejects(modify(b,target,{adult:1,child:0,infant:0}),/closed/);await assert.rejects(db.query('select cancel_customer_booking_v1($1)',[c.managementToken]),/closed/);await assert.rejects(book(dep,{adult:1,child:0,infant:0}),/unavailable/);await assert.rejects(db.query("select create_meeting_point_booking_v1($1,$2,$3,'Customer','test@example.test')",[op,hold.id,session]),/inactive|expired/i);}
 }
});
test('Tirane cutoff ignores SQL session timezone and follows DST',async()=>{for(const zone of ['UTC','Europe/London','America/New_York','Australia/Sydney']){await db.exec(`set timezone='${zone}'`);for(const [date,expected] of [['2030-03-30','2030-03-30T07:45:00.000Z'],['2030-03-31','2030-03-31T06:45:00.000Z'],['2030-10-26','2030-10-26T06:45:00.000Z'],['2030-10-27','2030-10-27T07:45:00.000Z']]){const r=(await db.query("select booking_cutoff_v1($1,'09:00') c",[date])).rows[0].c;assert.equal(new Date(r).toISOString(),expected);}}});
test('party availability compares occupied seats rather than passenger total',()=>{const q=quoteAvailability({version:1,operatorId:op,productId:product,date:'2030-06-01',guests:4,passengers:{adult:2,child:1,infant:1}},{operator_id:op,product_id:product,service_date:'2030-06-01',as_of:'2030-06-01',pricing_rules:{version:1,model:'per_guest',currency:'EUR',unit_price:1000},departures:[{id:'a',start_time:'13:00',capacity:8,committed:5,held:0},{id:'b',start_time:'15:00',capacity:8,committed:6,held:0}]});assert.equal(q.departures[0].available,true);assert.equal(q.departures[1].available,false);});

test('own three seats plus other five cannot grow; infant-only changes leave occupancy unchanged',async()=>{
 await setTestClock(db,'2030-06-03T06:00:00Z');const d=await departure('13:00','2030-06-03');const b=await book(d,{adult:3,child:0,infant:0});await book(d,{adult:5,child:0,infant:0});await assert.rejects(modify(b,d,{adult:4,child:0,infant:0}),/capacity/);assert.equal((await read(b)).occupiedSeats,3);const result=await modify(b,d,{adult:3,child:0,infant:2});assert.equal(result.occupiedSeats,3);assert.equal(result.total,3000);assert.equal(result.counts.infant,2);
});
test('an otherwise modifiable booking cannot move to a closed target; hold started before cutoff cannot confirm after it',async()=>{
 await setTestClock(db,'2030-06-04T06:00:00Z');const d=await departure('13:00','2030-06-04'),later=await departure('15:00','2030-06-04');const b=await book(later,{adult:1,child:0,infant:0});await setTestClock(db,'2030-06-04T10:44:00Z');const h=(await db.query('select * from create_hold_v1($1,$2,$3,$4,1)',[op,d,session,randomUUID()])).rows[0];assert.equal(new Date(h.expires_at).toISOString(),'2030-06-04T10:45:00.000Z');await setTestClock(db,'2030-06-04T10:45:00Z');await assert.rejects(modify(b,d,{adult:1,child:0,infant:0}),/closed/);await assert.rejects(db.query("select create_meeting_point_booking_v1($1,$2,$3,'Test','test@example.test')",[op,h.id,session]),/inactive/i);assert.equal((await read(b)).departureId,later);
});
test('management RPCs reject direct anonymous/authenticated execution',async()=>{for(const role of ['anon','authenticated']){await db.exec('begin;set local role '+role);try{await assert.rejects(db.query('select customer_booking_v1($1)',['a'.repeat(64)]),e=>e.code==='42501');}finally{await db.exec('rollback');}}});
test('cancel then rebook preserves history, releases exact occupied seats once, and creates independent notifications',async()=>{
 await setTestClock(db,'2030-06-05T06:00:00Z');
 for(const counts of [{adult:2,child:0,infant:0},{adult:2,child:2,infant:0},{adult:2,child:1,infant:1}]){
 const d=await departure('13:00','2030-06-05'),b=await book(d,counts);
 const occupied=async()=>Number((await db.query("select coalesce(sum(occupied_seats),0) n from booking_items where departure_id=$1 and status='confirmed'",[d])).rows[0].n);
 assert.equal(await occupied(),counts.adult+counts.child);
 await db.query('select cancel_customer_booking_v1($1)',[b.managementToken]);await db.query('select cancel_customer_booking_v1($1)',[b.managementToken]);assert.equal(await occupied(),0);assert.equal((await read(b)).status,'cancelled');
 assert.equal((await db.query("select count(*)::int n from domain_events where event_type='order.cancelled' and payload->>'orderId'=$1",[b.orderId])).rows[0].n,1);
 const fresh=await book(d,counts);assert.notEqual(fresh.orderId,b.orderId);assert.notEqual(fresh.bookingReference,b.bookingReference);assert.notEqual(fresh.managementToken,b.managementToken);assert.equal(await occupied(),counts.adult+counts.child);assert.equal((await read(b)).status,'cancelled');assert.equal((await read(fresh)).status,'confirmed');
 }
});
