import {test} from 'node:test';import assert from 'node:assert/strict';import {registerHooks} from 'node:module';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';import {readFileSync,writeFileSync} from 'node:fs';
import {initialWebsiteContent} from '../../src/modules/content/website-schema.ts';
registerHooks({load(url,c,next){if(url.endsWith('.module.css'))return {format:'module',source:'export default {}',shortCircuit:true};return next(url,c);}});
const {Footer}=await import('../../src/components/public/ui.tsx');const {BookingProvider}=await import('../../src/components/public/booking.tsx');const {LegalPage}=await import('../../src/components/public/legal-page.tsx');const h=React.createElement;
const c={...initialWebsiteContent,'final.showOnHomepage':'false',...Object.fromEntries(['instagram','facebook','getYourGuide','tripadvisor'].map(id=>['footer.social.'+id,'https://example.com/'+id]))};
const render=(content,path='/')=>renderToStaticMarkup(h(BookingProvider,null,h(Footer,{content,previewPathname:path,googleReviewsUrl:'https://www.google.com/maps'})));
test('one compact footer has all configured icons, legal links and staff button across public routes',()=>{for(const path of ['/','/book','/route','/tour','/explore','/explore/castle','/your-day','/booking/manage','/privacy-policy','/terms-and-conditions','/credits']){const html=render(c,path);assert.equal((html.match(/<footer/g)||[]).length,1);for(const label of ['Instagram','Facebook','GetYourGuide','Tripadvisor','Google Reviews','Privacy Policy','Terms &amp; Conditions','Staff Login','M66526001A'])assert.ok(html.includes(label),label);assert.equal((html.match(/target="_blank" rel="noopener noreferrer"/g)||[]).length,5);assert.ok(!html.includes('Photography credits'));assert.ok(!html.includes('More languages coming soon'));assert.match(html,/href="\/admin"/);}});
test('unset social profiles are hidden and legal text is never rendered as HTML',()=>{const html=render({...initialWebsiteContent,'final.showOnHomepage':'false'});assert.ok(!html.includes('aria-label="Instagram"'));const legal=renderToStaticMarkup(h(LegalPage,{kind:'privacy',content:{...c,'legal.privacy.status':'published','legal.privacy.text':'<script>alert(1)</script>'}}));assert.ok(legal.includes('&lt;script&gt;'));assert.ok(!legal.includes('<script>'));assert.ok(renderToStaticMarkup(h(LegalPage,{kind:'terms',content:c})).includes('not been published'));});
if(process.env.FOOTER_EVIDENCE){const css=['src/app/brand-tokens.css','src/app/globals.css','src/app/(public)/public.css'].map(p=>readFileSync(p,'utf8')).join('\n');writeFileSync('private/footer-evidence.html','<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><base href="http://localhost:3000/"><style>'+css+'</style></head><body><div class="public-site">'+render(c)+'</div></body></html>');}
