"use client";
import { meetingPoint } from "@/modules/booking/meeting-point";

import { useEffect, useRef, useState } from 'react';
import type { AvailabilityQuote } from '@/modules/booking/contracts';
import { passengerKeys, passengerLabels, ageLabel, passengerCount, type PassengerCounts } from '@/modules/booking/passengers';
import { displayMoney } from './use-availability';
import styles from './customer-booking.module.css';
type Booking={reference:string;status:string;version:number;date:string;time:string;departureId:string;counts:PassengerCounts;occupiedSeats:number;total:number;currency:string;cutoff:string;canManage:boolean;requiresStaff:boolean};
const messages:Record<string,string>={NOT_FOUND:'This booking link is invalid. Please check your confirmation.',CLOSED:'Online changes for this departure are now closed.',CONTACT_OPERATOR:'Please contact the operator to change this booking.',CHANGED:'The booking or price changed. Reload and review it again.',SOLD_OUT:'There are not enough seats. Your original booking is unchanged.',INVALID_REQUEST:'Please check the date and passengers.',ADULT_REQUIRED:'At least one adult is required for children or infants.',UNAVAILABLE:'Unable to confirm the result. Retry or reload your booking before making another change.'};
export function CustomerBooking(){
 const heading=useRef<HTMLHeadingElement>(null);
 const token=useRef('');const request=useRef('');const [booking,setBooking]=useState<Booking>();const [mode,setMode]=useState<'view'|'modify'|'review'|'cancel'>('view');const [date,setDate]=useState('');const [counts,setCounts]=useState<PassengerCounts>({adult:1,child:0,infant:0});const [departure,setDeparture]=useState('');const [quote,setQuote]=useState<AvailabilityQuote>();const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{heading.current?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});},[mode]);
 async function call(body:Record<string,unknown>,signal?:AbortSignal){const r=await fetch('/api/public/booking-management',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,token:token.current}),signal:signal??AbortSignal.timeout(20000),cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(messages[data.error]??messages.UNAVAILABLE);return data;}
 async function reload(){setBusy(true);setError('');try{setBooking(await call({action:'read'}));setMode('view');}catch(e){setError(e instanceof Error?e.message:messages.UNAVAILABLE);}finally{setBusy(false);}}
 useEffect(()=>{token.current=new URLSearchParams(location.hash.slice(1)).get('token')??'';const timer=setTimeout(()=>void reload(),0);return()=>clearTimeout(timer);/* Initial credential is kept out of request URLs. */ // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 useEffect(()=>{if(mode!=='modify'||!date)return;const controller=new AbortController();const timer=setTimeout(async()=>{setLoading(true);setQuote(undefined);setError('');try{passengerCount(counts);const result=await call({action:'availability',date,counts},controller.signal);if(!controller.signal.aborted)setQuote(result);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:messages.UNAVAILABLE);}finally{if(!controller.signal.aborted)setLoading(false);}},200);return()=>{clearTimeout(timer);controller.abort();};},[date,counts,mode]);
 // Quotes are only current if both party and date still match the request.
 const current=quote?.date===date&&quote.guests===passengerKeys.reduce((n,k)=>n+counts[k],0)&&(!quote.departures.length || passengerKeys.every(k=>quote.departures[0]?.passengerQuote?.counts[k]===counts[k]))?quote:undefined;
 const selected=current?.departures.find(d=>d.id===departure&&d.available);
 const price=selected?.passengerQuote;
 async function commit(action:'modify'|'cancel'){if(!booking)return;setBusy(true);setError('');try{const result=await call(action==='cancel'?{action}:{action,version:booking.version,departureId:departure,counts,total:price?.total,requestId:request.current});setBooking(result);setMode('view');}catch(e){setError(e instanceof Error?e.message:messages.UNAVAILABLE);}finally{setBusy(false);}}
 function edit(){if(!booking)return;setDate(booking.date);setCounts(booking.counts);setDeparture(booking.departureId);setQuote(undefined);setError('');setMode('modify');}
 return <section className={styles.card} aria-busy={busy}>
  <h1 ref={heading} tabIndex={-1}>Manage your booking</h1>
  {error&&<p role="alert">{error}</p>}
  {!booking?<><p>{busy?'Loading booking…':'Use the private link in your confirmation.'}</p><button className="p-button" disabled={busy} onClick={()=>void reload()}>Reload booking</button></>:<>
   <p><strong>{booking.reference}</strong> · {booking.status}</p>
   {(mode==='view'||mode==='cancel')&&<dl className={styles.summary}><div><dt>Your day</dt><dd>{booking.date} · {booking.time.slice(0,5)} (Europe/Tirane)</dd></div><div><dt>Passengers</dt><dd>{passengerKeys.map(k=><div key={k}>{booking.counts[k]} {passengerLabels[k]}</div>)}</dd></div><div><dt>Occupied seats</dt><dd>{booking.occupiedSeats}</dd></div><div><dt>Total</dt><dd>{displayMoney(booking.total,booking.currency)}</dd></div><div><dt>Meeting point</dt><dd><a href={meetingPoint.url} target="_blank" rel="noreferrer">{meetingPoint.label}</a></dd></div></dl>}
   {mode==='view'&&<>{booking.canManage?<div className={styles.actions}><button className="p-button p-button-booking" onClick={edit}>Modify booking</button><button className="p-button" onClick={()=>setMode('cancel')}>Cancel booking</button></div>:booking.status==='confirmed'?<p>{booking.requiresStaff?'Contact the operator for changes.':'Online modifications for this departure are now closed. Online cancellation for this departure is now closed.'}</p>:<p>This booking is cancelled.</p>}<button className="p-text-button" disabled={busy} onClick={()=>void reload()}>Reload booking</button></>}
   {mode==='modify'&&<><h2>Choose your updated trip</h2><label>Your date<input type="date" value={date} onChange={e=>{setDate(e.target.value);setDeparture('');}} /></label><div className={styles.passengers}>{passengerKeys.map(k=><div key={k}><span>{passengerLabels[k]}{current?.categories&&<small>{ageLabel(current.categories[k])}</small>}</span><button disabled={counts[k]===0||(k==='adult'&&counts.adult===1)} aria-label={'Remove one '+k} onClick={()=>setCounts({...counts,[k]:counts[k]-1})}>−</button><output>{counts[k]}</output><button disabled={counts[k]>=99} aria-label={'Add one '+k} onClick={()=>setCounts({...counts,[k]:counts[k]+1})}>+</button></div>)}</div><p role="status">{loading?'Checking availability…':'Choose a departure. Infants do not occupy seats.'}</p><div className={styles.departures}>{current?.departures.map(d=><button disabled={!d.available} aria-pressed={departure===d.id} key={d.id} onClick={()=>setDeparture(d.id)}>{d.startTime.slice(0,5)}<br/>{d.remaining===0?'Sold out':!d.available?'Not enough seats':d.remaining+' seats available'}</button>)}</div>{current?.departures.length===0&&<p>No bookable departures on this date.</p>}<div className={styles.actions}><button className="p-button" onClick={()=>setMode('view')}>Back</button><button className="p-button p-button-booking" disabled={!price||loading} onClick={()=>{request.current=crypto.randomUUID();setMode('review');}}>Review changes</button></div></>}
   {mode==='review'&&price&&<><h2>Review changes</h2><p>{date} · {selected?.startTime.slice(0,5)}</p><p>{passengerKeys.map(k=>counts[k]+' '+passengerLabels[k]).join(', ')}</p><p>{counts.adult+counts.child} occupied seats</p><p>Current: {displayMoney(booking.total,booking.currency)}<br/>Updated: {displayMoney(price.total,booking.currency)}<br/>Difference: {displayMoney(price.total-booking.total,booking.currency)}</p><p>Updated total is payable at the meeting point.</p><div className={styles.actions}><button className="p-button" disabled={busy} onClick={()=>setMode('modify')}>Back</button><button className="p-button p-button-booking" disabled={busy} onClick={()=>void commit('modify')}>{busy?'Saving…':'Confirm modification'}</button></div></>}
   {mode==='cancel'&&<><h2>Cancel this booking?</h2><p>The booking above will be cancelled. This cannot be undone.</p><div className={styles.actions}><button className="p-button" disabled={busy} onClick={()=>setMode('view')}>Keep booking</button><button className="p-button" disabled={busy} onClick={()=>void commit('cancel')}>{busy?'Cancelling…':'Confirm cancellation'}</button></div></>}
  </>}
 </section>;
}
