import Link from 'next/link';
import { DayPlannerStrip } from './day-planner-strip';
import { BookingBar, BookButton } from './booking';
import { ActionLink, Media, SectionHeading } from './ui';
import { LiveMapEmbed } from './live-map-embed';
import { RoutePreview } from './route-preview';
import { GuestReviews } from './guest-reviews';
import { websitePlaces, type WebsiteContent } from '@/modules/content/website-schema';
import type { Homepage, HomeContent } from '@/modules/content/homepage';
import type { ReviewSelection } from '@/modules/content/reviews';
export function TourView({tour,c,reviews,places=websitePlaces(c)}:{tour:Homepage;c:WebsiteContent;reviews:ReviewSelection;places?:Array<ReturnType<typeof websitePlaces>[number]&{aliases?:string[]}>}){
 const p=tour.product;
 return <main id="main-content" className="p-subpage p-container">
 {!p&&<p role="status">Tour information is not available yet.</p>}
 <div className="p-tour-grid"><div><p className="p-eyebrow">{c['tourPage.eyebrow']}</p><h1>{p?.title??'Day tour'}</h1><p className="p-lead">{p?.description}</p><Media src={p?.ogImage??places[1].image} alt={p?.ogImageAlt??places[1].alt} hero/>
 <nav className="p-section-nav" aria-label="Tour sections"><a href="#tour-route">Route</a><a href="#included">Included</a><a href="#timetable">Timetable</a><a href="#tour-live">Live map</a><a href="#how">How it works</a>{reviews.reviews.length>0&&<a href="#reviews">Reviews</a>}<a href="#faq">FAQ</a></nav></div>
 <aside className="p-booking-card"><h2>{tour.price}</h2><p>{tour.frequency}</p><BookButton>{c['nav.book']}</BookButton><p>Reserve seats online. Pay at the meeting point.</p></aside></div>
 <section id="tour-route" className="p-section"><SectionHeading eyebrow={c['route.eyebrow']} title={c['route.title']}><p>{c['route.text']}</p></SectionHeading><ActionLink href="/live">{c['live.linkLabel']}</ActionLink><RoutePreview places={places} showNote={false}/></section>
 <section id="included" className="p-section p-narrow"><h2>{c['tourPage.includedTitle']}</h2><p>{p?.inclusions??'Ticket inclusions have not been published. Please confirm the details with staff.'}</p></section>
 <section id="timetable" className="p-section"><SectionHeading eyebrow={c['departures.eyebrow']} title={c['departures.title']}/><div className="p-empty"><h3>{tour.frequency}</h3>{tour.schedule==='ready'?<><p>{tour.date} | {tour.timezone}. Scheduled departures; check availability for your selected date.</p><ul className="p-departure-times">{tour.departures.map((d,i)=><li key={i}><time dateTime={`${tour.date}T${d.time}`}>{d.time}</time></li>)}</ul></>:<p>Check the booking page for availability on your selected date.</p>}<ActionLink href="/live">View boarding points</ActionLink></div></section>
 <section id="tour-live" className="p-section"><SectionHeading eyebrow={c['live.eyebrow']} title={c['live.title']}><p>{c['live.emphasis']}</p><p>{c['live.text']}</p></SectionHeading><LiveMapEmbed/><ActionLink href="/live">{c['live.linkLabel']}</ActionLink></section>
 <section id="how" className="p-section"><SectionHeading eyebrow={c['how.eyebrow']} title={c['how.title']}/><ol className="p-how">{[0,1,2,3].map(i=><li key={i}><h3>{c[`how.${i}.title`]}</h3><p>{c[`how.${i}.text`]}</p></li>)}</ol><BookingBar facts={{price:tour.price,frequency:tour.frequency}}/></section>
 {reviews.reviews.length>0&&<div id="reviews"><GuestReviews selection={reviews} eyebrow={c['reviews.eyebrow']} title={c['reviews.title']} subtitle={c['reviews.text']}/></div>}
 <section id="faq" className="p-section p-faq"><h2>{c['tourPage.faqTitle']}</h2><details><summary>{c['tourPage.faqBook']}</summary><p>Choose a date on the booking page to check available seats. Confirm online and pay at the meeting point.</p><ActionLink href="/book">{c['nav.book']}</ActionLink></details><details><summary>{c['tourPage.faqBoard']}</summary><p>Use the live map for the current boarding points and route.</p><ActionLink href="/live">{c['live.linkLabel']}</ActionLink></details><details><summary>{c['tourPage.faqFees']}</summary><p>{p?.inclusions??'Ticket inclusions have not been published. Please confirm the details with staff.'}</p></details><details><summary>{c['tourPage.faqLive']}</summary><p>Open the live map for the latest reported location, GPS status and available arrival estimates.</p><ActionLink href="/live">{c['live.linkLabel']}</ActionLink></details></section>
 </main>;
}
export function ExploreView({home,c,places=websitePlaces(c)}:{home:Homepage;c:WebsiteContent;places?:Array<ReturnType<typeof websitePlaces>[number]&{aliases?:string[]}>}){return <main id="main-content" className="p-subpage p-container"><p className="p-eyebrow">{c['explorePage.eyebrow']}</p><h1>{c['explorePage.title']}</h1><p className="p-lead">{c['explorePage.text']}</p>{places.map(place=><article className="p-guide-story" id={place.id} key={place.id}>{place.aliases?.filter(a=>a!==place.id).map(a=><span key={a} id={a} aria-hidden="true"/>)}<Media src={place.image} alt={place.alt}/><div><p className="p-eyebrow">{place.tag}</p><h2>{place.name}</h2><p className="p-lead">{place.text}</p><p>{place.detail}</p>{(place.link.startsWith("/explore/") || !place.aliases && home.content[`explore-${place.id}`])?<ActionLink href={`/explore/${place.id}`}>Read the guide</ActionLink>:<p className="p-preview">Full visitor guide coming soon.</p>}<BookButton>{c['nav.book']}</BookButton></div></article>)}</main>;}
export function LiveView({c,places=websitePlaces(c)}:{c:WebsiteContent;places?:Array<ReturnType<typeof websitePlaces>[number]&{aliases?:string[]}>}){return <main id="main-content" className="p-subpage p-container p-live-page"><p className="p-eyebrow">{c['live.eyebrow']}</p><h1>{c['live.title']}<br/><em>{c['live.emphasis']}</em></h1><p className="p-lead">{c['live.text']}</p><LiveMapEmbed priority/><section className="p-live-service" aria-label="Today?s service and tickets"><h2>Plan your ride</h2><DayPlannerStrip compact/><BookButton>Check availability</BookButton></section><section className="p-section"><SectionHeading eyebrow={c['route.eyebrow']} title={c['route.title']}/><RoutePreview places={places}/></section></main>;}
export function GuideView({content,place}:{content:HomeContent;place:ReturnType<typeof websitePlaces>[number]&{location?:string;mapsUrl?:string}}){return <><nav aria-label="Breadcrumb"><Link className="p-text-link" href="/explore">Explore Shkodra</Link></nav><article><p className="p-eyebrow">{place.tag}</p><h1>{content.title}</h1>{place.location&&<p>{place.location}</p>}{place.mapsUrl&&<a className="p-text-link" href={place.mapsUrl} target="_blank" rel="noopener noreferrer">View location on Google Maps</a>}<Media src={place.image} alt={place.alt} hero/><div className="p-section p-narrow p-guide-body">{content.text.split(/\n\s*\n/).map((p,i)=><p key={i}>{p}</p>)}</div></article></>;}
