import { ExpandableText } from "./expandable-text";
import { lowestQuotedFare, bookingDate } from "./booking-presentation";
import { BookingPriceIndicator } from "./booking-controls";
import Link from 'next/link';
import { DayPlannerStrip } from './day-planner-strip';
import { BookButton } from './booking';
import { ActionLink, Media, SectionHeading } from './ui';
import { LiveMapEmbed } from './live-map-embed';
import { RoutePreview } from './route-preview';
import { sectionVisible, websitePlaces, type WebsiteContent } from '@/modules/content/website-schema';
import type { Homepage, HomeContent } from '@/modules/content/homepage';
export function TourView({tour,c,places=websitePlaces(c)}:{tour:Homepage;c:WebsiteContent;places?:Array<ReturnType<typeof websitePlaces>[number]&{aliases?:string[]}>}){
 const p=tour.product;
 return <main id="main-content" className="p-subpage p-container">
 {!p&&<p role="status">Tour information is not available yet.</p>}
 <div className="p-tour-grid"><div><p className="p-eyebrow">{c['tourPage.eyebrow']}</p><h1>{p?.title??'Day tour'}</h1><ExpandableText text={p?.description ?? ""} className="p-lead"/><Media src={p?.ogImage??c['hero.desktop']} alt={p?.ogImageAlt??c['hero.alt']} hero/>
 <nav className="p-section-nav" aria-label="Tour sections">{sectionVisible(c,'route')&&<a href="#tour-route">Route</a>}<a href="#included">Included</a>{sectionVisible(c,'departures')&&<a href="#timetable">Timetable</a>}{sectionVisible(c,'live')&&<a href="#tour-live">Live map</a>}</nav></div>
 <aside className="p-booking-card"><BookingPriceIndicator amount={lowestQuotedFare(tour.adultFares?.map(f=>f.amount)??[])} date={tour.date??undefined}/><p>{tour.frequency}</p><BookButton>{c['nav.book']}</BookButton><p>Reserve seats online. Pay at the meeting point.</p></aside></div>
 {sectionVisible(c,'route') && <section id="tour-route" className="p-section"><SectionHeading eyebrow={c['route.eyebrow']} title={c['route.title']}><ExpandableText text={c['route.text']}/></SectionHeading><ActionLink href="/route">{c['live.linkLabel']}</ActionLink><RoutePreview actionLabel={c["labels.destination"]} places={places} showNote={false}/></section>}
 <section id="included" className="p-section p-narrow"><h2>{c['tourPage.includedTitle']}</h2><p>{p?.inclusions??'Ticket inclusions have not been published. Please confirm the details with staff.'}</p></section>
 {sectionVisible(c,'departures') && <section id="timetable" className="p-section"><SectionHeading eyebrow={c['departures.eyebrow']} title={c['departures.title']}/><div className="p-empty"><h3>{tour.frequency}</h3>{tour.schedule==='ready'?<><p>{bookingDate(tour.date??"")}. Times shown in local Shkodra time. Scheduled departures; check availability for your selected date.</p><ul className="p-departure-times">{tour.departures.map((d,i)=><li key={i}><time dateTime={`${tour.date}T${d.time}`}>{d.time}</time></li>)}</ul></>:<p>Check the booking page for availability on your selected date.</p>}<ActionLink href="/route">View boarding points</ActionLink></div></section>}
 {sectionVisible(c,'live') && <section id="tour-live" className="p-section"><SectionHeading eyebrow={c['live.eyebrow']} title={c['live.title']}><p>{c['live.emphasis']}</p><p>{c['live.text']}</p></SectionHeading><LiveMapEmbed/><ActionLink href="/route">{c['live.linkLabel']}</ActionLink></section>}
 </main>;
}
export function ExploreView({home,c,places=websitePlaces(c)}:{home?:Homepage;c:WebsiteContent;places?:Array<ReturnType<typeof websitePlaces>[number]&{aliases?:string[]}>}){return <main id="main-content" className="p-subpage p-container"><p className="p-eyebrow">{c['explorePage.eyebrow']}</p><h1>{c['explorePage.title']}</h1><p className="p-lead">{c['explorePage.text']}</p>{places.map(place=><article className="p-guide-story" id={place.id} key={place.id}>{place.aliases?.filter(a=>a!==place.id).map(a=><span key={a} id={a} aria-hidden="true"/>)}<Media src={place.image} alt={place.alt}/><div><p className="p-eyebrow">{place.tag}</p><h2>{place.name}</h2><p className="p-lead">{place.text}</p><ExpandableText text={place.detail}/><div className="p-button-group">{(place.link.startsWith("/explore/") || !place.aliases && home?.content[`explore-${place.id}`])?<ActionLink href={`/explore/${place.id}`}>{c['labels.guide']}</ActionLink>:<p className="p-preview">Full visitor guide coming soon.</p>}<BookButton>{c['nav.book']}</BookButton></div></div></article>)}</main>;}
export function LiveView({c,places=websitePlaces(c)}:{c:WebsiteContent;places?:Array<ReturnType<typeof websitePlaces>[number]&{aliases?:string[]}>}){return <main id="main-content" className="p-subpage p-container p-live-page">{sectionVisible(c,'live')?<><p className="p-eyebrow">{c['live.eyebrow']}</p><h1>{c['live.title']}<br/><em>{c['live.emphasis']}</em></h1><p className="p-lead">{c['live.text']}</p></>:<h1>Live map</h1>}<LiveMapEmbed priority presentation="full"/><section className="p-live-service" aria-label="Today?s service and tickets"><h2>Plan your ride</h2><DayPlannerStrip compact/><BookButton>Check availability</BookButton></section>{sectionVisible(c,'route')&&<section className="p-section"><SectionHeading eyebrow={c['route.eyebrow']} title={c['route.title']}/><RoutePreview actionLabel={c["labels.destination"]} places={places}/></section>}</main>;}
export function GuideView({content,place}:{content:HomeContent;place:ReturnType<typeof websitePlaces>[number]&{location?:string;mapsUrl?:string}}){return <><nav aria-label="Breadcrumb"><Link className="p-text-link" href="/explore">Explore Shkodra</Link></nav><article><p className="p-eyebrow">{place.tag}</p><h1>{content.title}</h1>{place.location&&<p>{place.location}</p>}{place.mapsUrl&&<a className="p-text-link" href={place.mapsUrl} target="_blank" rel="noopener noreferrer">View location on Google Maps</a>}<Media src={place.image} alt={place.alt} hero/><div className="p-section p-narrow p-guide-body">{content.text.split(/\n\s*\n/).map((p,i)=><p key={i}>{p}</p>)}</div></article></>;}
