"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { blankDestination, destinationSlug, type Destination, type DestinationRecord } from "@/modules/content/destinations";
import type { DestinationStop } from "@/modules/content/destination-stops-server";
import { saveDestination } from "./destination-actions";
import { ImageField } from "./image-field";
import { ownerStatus } from "./presentation";
import styles from "./destinations.module.css";
export function DestinationsEditor({operatorId,records,stops,stopsAvailable,canPublish=false}:{canPublish?:boolean;operatorId:string;records:DestinationRecord[];stops:DestinationStop[];stopsAvailable:boolean}) {
  const [confirmation,setConfirmation]=useState<"discard"|"archive"|null>(null);
  const router=useRouter(); const [selected,setSelected]=useState<DestinationRecord|null|undefined>();
  const [value,setValue]=useState<Destination>(blankDestination),[order,setOrder]=useState(0),[message,setMessage]=useState(""),[pending,start]=useTransition(),[slugEdited,setSlugEdited]=useState(false);
  function open(r:DestinationRecord|null){setSelected(r);setValue(r?.body??{...blankDestination});setOrder(r?.destination_order??records.length);setSlugEdited(Boolean(r));setMessage("");}
  function update<K extends keyof Destination>(key:K,v:Destination[K]){setValue(d=>({...d,[key]:v}));}
  function save(op:string,r=selected){start(async()=>{const result=await saveDestination(operatorId,r?.id??null,r?.updated_at??null,value,op,order);if(result.error)setMessage(result.error);else{setMessage(op==="draft"?"Draft saved. The public destination is unchanged.":"Destination updated.");setSelected(undefined);router.refresh();}});}
  return <section className={styles.manager}><header><div><h1>Destinations</h1><p>Manage the places visitors can discover on the website.</p></div><Button disabled={selected!==undefined} onClick={()=>open(null)}>Add Destination</Button></header>
    {confirmation&&<div role="alert"><p>{confirmation==="discard"?"Discard your unsaved destination changes?":"Archive this destination? Associated route stops and operational history will remain unchanged."}</p><Button onClick={()=>{if(confirmation==="discard")setSelected(undefined);else save("archive");setConfirmation(null);}}>Confirm {confirmation}</Button><Button className="ss-button--outline" onClick={()=>setConfirmation(null)}>Keep editing</Button></div>}
    {message&&<p role="status">{message}</p>}
    {selected===undefined?<div className={styles.list}>{records.length===0&&<p>No destinations yet. Add your first destination.</p>}{records.map((r,i)=><article key={r.id}><div><span className={styles.number}>{String(i+1).padStart(2,"0")}</span><h2>{r.body.name}</h2><span>{ownerStatus(r.status)}{r.status==="published"&&JSON.stringify(r.body)!==JSON.stringify(r.published_body)?" · Draft changes":""}</span></div><div className={styles.actions}><Button onClick={()=>open(r)}>Edit</Button><Button className="ss-button--outline" disabled={!canPublish||pending||i===0} onClick={()=>start(async()=>{const result=await saveDestination(operatorId,r.id,r.updated_at,r.body,"earlier",r.destination_order);setMessage(result.error??"Order updated.");router.refresh();})}>Move earlier</Button><Button className="ss-button--outline" disabled={pending||i===records.length-1} onClick={()=>start(async()=>{const result=await saveDestination(operatorId,r.id,r.updated_at,r.body,"later",r.destination_order);setMessage(result.error??"Order updated.");router.refresh();})}>Move later</Button></div></article>)}</div>:<form onSubmit={e=>{e.preventDefault();save("draft");}}>
      <div className={styles.actions}><Button type="button" className="ss-button--outline" onClick={()=>{if(JSON.stringify(value)!==JSON.stringify(selected?.body??blankDestination)){setConfirmation("discard");return;}setSelected(undefined);}}>Back to destinations</Button>{selected&&<a className="ss-button ss-button--outline" href={`/admin/${operatorId}/destination-preview?id=${selected.id}`} target="_blank" rel="noreferrer">Preview saved draft</a>}</div>
      <fieldset disabled={pending}><legend>{selected?"Edit Destination":"Add Destination"}</legend><div className={styles.fields}>
        <label>Destination name<input required maxLength={200} value={value.name} onChange={e=>{update("name",e.target.value);if(!slugEdited)update("slug",destinationSlug(e.target.value));}}/></label>
        <details><summary>Advanced: page address</summary><label>Page address<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={150} value={value.slug} onChange={e=>{setSlugEdited(true);update("slug",e.target.value);}}/></label><p>Changing this address affects links to this destination when published.</p></details>
        {([['tag','Short label / subtitle'],['text','Short description'],['detail','Destination summary'],['story','Full story'],['location','Address / location label'],['mapsUrl','Google Maps link'],['seoTitle','Search result title'],['seoDescription','Search result description']] as const).map(([key,label])=><label key={key}>{label}{['text','detail','story','seoDescription'].includes(key)?<textarea rows={key==='story'?8:3} value={value[key]} maxLength={key==='story'?50000:2000} onChange={e=>update(key,e.target.value)}/>:<input value={value[key]} maxLength={2000} onChange={e=>update(key,e.target.value)}/>}</label>)}
        <ImageField operatorId={operatorId} label="Main image" value={value.image} onChange={v=>update("image",v)}/>
        <label>Image description<input value={value.alt} onChange={e=>update("alt",e.target.value)}/></label><ImageField operatorId={operatorId} label="Social sharing image" value={value.socialImage} onChange={v=>update("socialImage",v)} optional/>
        <p>Map coordinates are retained for compatibility but are not used to position operational stops. Manage stops in the independent Live Map.</p>
        <label>Associated Hop-On Hop-Off stop<select value={value.stopId??""} onChange={e=>update("stopId",e.target.value||null)}><option value="">No associated stop</option>{value.stopId&&!stops.some(s=>s.id===value.stopId)&&<option value={value.stopId}>Previously associated stop (currently unavailable)</option>}{stops.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select>{!stopsAvailable&&<small>Published route stops are currently unavailable. You can save a destination without a stop; existing references are preserved.</small>}</label>
        <p>Use Move earlier / Move later in the list to change published ordering. These are immediate publisher actions; saving a story draft does not reorder published cards.</p>
        <label><input type="checkbox" checked={value.showOnPage} onChange={e=>update("showOnPage",e.target.checked)}/> Show on Destinations page</label><label><input type="checkbox" checked={value.showOnHomepage} onChange={e=>update("showOnHomepage",e.target.checked)}/> Show in homepage destination links</label>
      </div><div className={styles.actions}><Button type="submit">Save Draft</Button><Button type="button" disabled={!canPublish} onClick={()=>save("publish")}>Publish</Button>{selected?.status==='published'&&<Button type="button" className="ss-button--outline" disabled={!canPublish} onClick={()=>save("unpublish")}>Unpublish</Button>}{selected&&<Button type="button" className="ss-button--outline" disabled={!canPublish} onClick={()=>{setConfirmation("archive");}}>Archive destination</Button>}</div></fieldset>
    </form>}
  </section>;
}
