"use client";
import {useState,useTransition,useRef} from 'react';
import {useRouter} from 'next/navigation';
import {Button} from '@/components/ui/button';
import {passengerKeys,passengerLabels,type PassengerCategories,type PassengerSnapshot} from '@/modules/booking/passengers';
import {saveCalendar,savePassengerPricing} from './calendar-actions';
import type {ServiceSchedule,ScheduleTime} from './schedule-editor';
import styles from './calendar.module.css';
export type CalendarSlot={id:string|null;time:string;capacity:number;open:boolean;booked:number;held:number;remaining:number;quote:PassengerSnapshot|null};
export type CalendarDay={date:string;slots:CalendarSlot[];range:Settings|null;exception:{calendar_settings:Settings;closed:boolean;departure_times:ScheduleTime[]}|null};
type Offer={name:string;label:string;type:'fixed'|'percent'|'amount';values:Partial<Record<'adult'|'child'|'infant',number>>;times?:string[]};
type Settings={closed?:boolean;times?:ScheduleTime[];capacity?:number;prices?:Partial<Record<'adult'|'child'|'infant',number>>;offer?:Offer;departures?:Record<string,Settings>};
const money=(n:number)=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(n/100);
function PriceFields({value,onChange,percent=false}:{value:Settings['prices'];onChange:(v:Settings['prices'])=>void;percent?:boolean}) {return <div className={styles.prices}>{passengerKeys.map(k=><label key={k}>{passengerLabels[k]} ({percent?'%':'EUR'})<input type="number" min="0" max={percent?100:9999999} step={percent?1:0.01} placeholder="Inherit" value={value?.[k]===undefined?'':value[k]!/(percent?1:100)} onChange={e=>{const next={...value};if(e.target.value==='')delete next[k];else next[k]=Math.round(Number(e.target.value)*(percent?1:100));onChange(next);}}/></label>)}</div>;}
export function StandardPricing({operatorId,productId,stamp,categories}:{operatorId:string;productId:string;stamp:string;categories:PassengerCategories}) {
 const [value,setValue]=useState(categories),[message,setMessage]=useState(''),[pending,start]=useTransition();const router=useRouter();
 return <form onSubmit={e=>{e.preventDefault();start(async()=>{const r=await savePassengerPricing(operatorId,productId,stamp,value);setMessage(r.error??'Standard pricing saved. Existing bookings keep their agreed prices.');if(!r.error)router.refresh();});}}><h3>Passenger categories &amp; standard pricing</h3><p>All passengers use one seat, including passengers with a zero-price ticket.</p><div className={styles.prices}>{passengerKeys.map(k=><fieldset key={k} disabled={pending}><legend>{passengerLabels[k]}</legend><label>Minimum age<input required type="number" min={0} max={150} value={value[k].min} onChange={e=>setValue({...value,[k]:{...value[k],min:Number(e.target.value)}})}/></label>{k!=='adult'?<label>Maximum age<input required type="number" min={0} max={150} value={value[k].max??''} onChange={e=>setValue({...value,[k]:{...value[k],max:Number(e.target.value)}})}/></label>:<p>No maximum age</p>}<label>Standard price (EUR)<input type="number" min={0} max={9999999} step="0.01" required value={value[k].price===null?'':value[k].price!/100} onChange={e=>setValue({...value,[k]:{...value[k],price:e.target.value===''?null:Math.round(Number(e.target.value)*100)}})}/></label></fieldset>)}</div><Button disabled={pending}>Save Standard Pricing</Button>{message&&<p role="status">{message}</p>}</form>;
}
export function OperationsCalendar({operatorId,schedule,days,month,today}:{operatorId:string;schedule:ServiceSchedule;days:CalendarDay[];month:string;today:string}) {
 const editor=useRef<HTMLFormElement>(null);const [newTime,setNewTime]=useState('');
 const router=useRouter(),[from,setFrom]=useState(''),[to,setTo]=useState(''),[weekdays,setWeekdays]=useState([1,2,3,4,5,6,7]),[settings,setSettings]=useState<Settings>({}),[message,setMessage]=useState(''),[confirmed,setConfirmed]=useState(false),[pending,start]=useTransition();
 const selected=days.find(d=>d.date===from),offset=(new Date(month+'T12:00:00Z').getUTCDay()+6)%7;
 function navigate(delta:number){const d=new Date(month+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+delta);router.push(`?date=${d.toISOString().slice(0,10)}`);}
 function open(day:CalendarDay){requestAnimationFrame(()=>editor.current?.scrollIntoView({block:'start',behavior:'smooth'}));setFrom(day.date);setTo(day.date);setConfirmed(false);setMessage('');setSettings(day.exception?{...day.exception.calendar_settings,closed:day.exception.closed,times:day.exception.departure_times}:{times:day.slots.filter(s=>s.open).map(s=>({time:s.time})),closed:!day.slots.some(s=>s.open)});}
 function apply(restore=false){start(async()=>{const r=await saveCalendar(operatorId,schedule.id,schedule.updated_at,{from,to,weekdays,settings,confirmed,restore});setMessage(r.error??'Calendar saved. Existing bookings are unchanged.');if(!r.error){router.refresh();setFrom('');}});}
 function departure(time:string,value:Settings){setSettings({...settings,departures:{...settings.departures,[time]:value}});}
 return <section className={styles.workspace}><header className={styles.toolbar}><Button className="ss-button--outline" onClick={()=>navigate(-1)}>Previous</Button><h2>{new Date(month+'T12:00:00Z').toLocaleDateString('en-GB',{month:'long',year:'numeric',timeZone:'UTC'})}</h2><Button className="ss-button--outline" onClick={()=>navigate(1)}>Next</Button><Button onClick={()=>router.push('?date='+today)}>Today</Button><Button onClick={()=>{setFrom(today<schedule.start_date?schedule.start_date:today);setTo(schedule.end_date);setSettings({});setConfirmed(false);}}>Select Date Range</Button></header>
 <div className={styles.grid}>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><span className={styles.weekday} key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{days.map(day=>{const open=day.slots.filter(s=>s.open),prices=open.flatMap(s=>s.quote?[s.quote.total]:[]),booked=day.slots.reduce((n,s)=>n+s.booked,0),sold=open.length>0&&open.every(s=>s.remaining===0),special=open.some(s=>s.quote?.lines.some(l=>l.offer));return <button type="button" key={day.date} className={styles.day} aria-pressed={from===day.date} aria-current={day.date===today?'date':undefined} onClick={()=>openDay(day)}><strong>{Number(day.date.slice(-2))}</strong><span>{open.length?'Open':'Closed'}</span>{!!open.length&&<small>{open.length} departures</small>}{!!prices.length&&<small>From {money(Math.min(...prices))}</small>}{special&&<small>Special</small>}{(day.range||day.exception)&&<small>Modified</small>}{booked>0&&<small>{booked} booked</small>}{sold&&<small>Sold out</small>}</button>;function openDay(d:CalendarDay){openEditor(d);}})}</div>
 <details><summary>Saved range overrides</summary>{schedule.calendar_ranges?.length?schedule.calendar_ranges.map((r,i)=><p key={i}><Button className="ss-button--outline" onClick={()=>{setFrom(r.from);setTo(r.to);setWeekdays(r.weekdays);setSettings(r as Settings);setConfirmed(false);}}>{r.from} to {r.to}</Button></p>):<p>No range overrides.</p>}</details>
 {message&&<p role="status">{message}</p>}
 {from&&<form ref={editor} className={styles.editor} onSubmit={e=>{e.preventDefault();apply();}}><h3>{from===to?'Edit date':'Edit date range'}</h3><fieldset disabled={pending}><div className={styles.prices}><label>From<input type="date" required min={schedule.start_date>today?schedule.start_date:today} max={schedule.end_date} value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" required min={from} max={schedule.end_date} value={to} onChange={e=>setTo(e.target.value)}/></label><label>Operating<select value={settings.closed===undefined?'inherit':settings.closed?'closed':'open'} onChange={e=>setSettings({...settings,closed:e.target.value==='inherit'?undefined:e.target.value==='closed'})}><option value="inherit">Use inherited schedule</option><option value="open">Open</option><option value="closed">Closed</option></select></label></div>
 {from!==to&&<fieldset><legend>Apply on weekdays</legend><p>The latest saved matching range wins. Individual date and departure overrides take priority.</p><div className={styles.toolbar}>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((d,i)=><label key={d}><input type="checkbox" checked={weekdays.includes(i+1)} onChange={e=>setWeekdays(e.target.checked?[...weekdays,i+1]:weekdays.filter(v=>v!==i+1))}/>{d}</label>)}</div></fieldset>}
 <label>Capacity per departure<input type="number" min="1" max="999999" placeholder="Inherit" value={settings.capacity??''} onChange={e=>setSettings({...settings,capacity:e.target.value?Number(e.target.value):undefined})}/></label>
 <fieldset><legend>Departure times</legend><p>{settings.times?'Custom times for the selected dates.':'Using inherited departure times.'}</p><div className={styles.toolbar}>{(settings.times??schedule.departure_times).map(t=><span key={t.time}>{t.time} <Button type="button" size="sm" className="ss-button--outline" aria-label={'Remove '+t.time} onClick={()=>setSettings({...settings,times:(settings.times??schedule.departure_times).filter(v=>v.time!==t.time)})}>Remove</Button></span>)}</div><div className={styles.toolbar}><label>New departure time<input type="time" value={newTime} onChange={e=>setNewTime(e.target.value)}/></label><Button type="button" onClick={()=>{if(!newTime||(settings.times??schedule.departure_times).some(t=>t.time===newTime)){setMessage('Choose a new departure time.');return;}setSettings({...settings,times:[...(settings.times??schedule.departure_times),{time:newTime}].sort((a,b)=>a.time.localeCompare(b.time))});setNewTime('');}}>Add Departure</Button><Button type="button" className="ss-button--outline" onClick={()=>setSettings({...settings,times:undefined})}>Use inherited times</Button></div></fieldset>
 <h4>Price overrides</h4><p>Leave a category blank to inherit its price.</p><PriceFields value={settings.prices} onChange={prices=>setSettings({...settings,prices})}/>
 {from===to&&<><h4>Departures</h4>{(settings.times??selected?.slots.map(s=>({time:s.time}))??[]).map(({time})=>{const slot=selected?.slots.find(s=>s.time===time),value=settings.departures?.[time]??{};return <details key={time}><summary>{time} · {slot?.booked??0} booked · {slot?.remaining??settings.capacity??schedule.default_capacity} available</summary><label><input type="checkbox" checked={!value.closed} onChange={e=>departure(time,{...value,closed:!e.target.checked})}/> Open for new bookings</label><label>Capacity<input type="number" min="1" placeholder="Inherit" value={value.capacity??''} onChange={e=>departure(time,{...value,capacity:e.target.value?Number(e.target.value):undefined})}/></label><PriceFields value={value.prices} onChange={prices=>departure(time,{...value,prices})}/>{slot?.quote?.lines.map(l=><p key={l.category}>Effective {l.category}: {money(l.unitPrice)}</p>)}{slot?.booked? <a href={`/admin/${operatorId}/bookings`}>Inspect bookings</a>:null}</details>;})}<Button type="button" className="ss-button--outline" onClick={()=>setSettings({...settings,closed:true})}>Close Entire Day</Button></>}
 <details><summary>Special offer</summary><label>Offer name<input maxLength={100} value={settings.offer?.name??''} onChange={e=>setSettings({...settings,offer:{type:'fixed',values:{},label:'',...settings.offer,name:e.target.value}})}/></label>{settings.offer&&<><label>Public label<input maxLength={100} value={settings.offer.label} onChange={e=>setSettings({...settings,offer:{...settings.offer!,label:e.target.value}})}/></label><label>Offer type<select value={settings.offer.type} onChange={e=>setSettings({...settings,offer:{...settings.offer!,type:e.target.value as Offer['type'],values:{}}})}><option value="fixed">Fixed price</option><option value="percent">Percentage discount</option><option value="amount">Fixed amount discount</option></select></label><PriceFields percent={settings.offer.type==='percent'} value={settings.offer.values} onChange={values=>setSettings({...settings,offer:{...settings.offer!,values:values??{}}})}/><label>Apply to times (blank = all)<input value={settings.offer.times?.join(', ')??''} onChange={e=>setSettings({...settings,offer:{...settings.offer!,times:e.target.value?e.target.value.split(',').map(t=>t.trim()):undefined}})}/></label><Button type="button" onClick={()=>setSettings({...settings,offer:undefined})}>Remove offer</Button></>}</details>
 <p>Closing sales does not cancel existing bookings. Capacity cannot be reduced below confirmed passengers and active holds.</p><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I confirm closing affected departures with reservations. Existing bookings must remain.</label><div className={styles.toolbar}><Button>Apply to Selected Dates</Button><Button type="button" className="ss-button--outline" onClick={()=>apply(true)}>Restore inherited rules</Button><Button type="button" className="ss-button--outline" onClick={()=>setFrom('')}>Close editor</Button></div></fieldset></form>}
 </section>;
 function openEditor(day:CalendarDay){open(day);}
}
