import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync} from 'node:fs';
import ts from 'typescript';
import {editableWebsiteSections} from '../src/modules/content/website-schema';
import {ownerFieldLabel} from '../src/app/admin/presentation';

// Source inventory, not a claim of exhaustive browser interaction coverage.
const files=execFileSync('git',['ls-files','src/app/admin','src/app/auth'],{encoding:'utf8'}).trim().split(/\r?\n/).filter(f=>/\.tsx?$/.test(f));
type Item={file:string;line:number;before:string;classification:string;note:string};
const items:Item[]=[];
for(const file of files){
 const before=execFileSync('git',['show',`HEAD:${file}`],{encoding:'utf8'}),after=readFileSync(file,'utf8');
 const source=ts.createSourceFile(file,before,ts.ScriptTarget.Latest,true,file.endsWith('tsx')?ts.ScriptKind.TSX:ts.ScriptKind.TS);
 const seen=new Set<string>();
 function visit(node:ts.Node){
  let text='';
  if(ts.isJsxText(node))text=node.text.trim();
  if(ts.isStringLiteral(node)||ts.isNoSubstitutionTemplateLiteral(node)){
   const parent=node.parent;
   if(ts.isJsxAttribute(parent)&&['title','placeholder','aria-label','label'].includes(parent.name.getText(source)))text=node.text;
   else if(ts.isPropertyAssignment(parent)&&['label','description','title'].includes(parent.name.getText(source)))text=node.text;
   else if(/^[A-Z][A-Za-z]+ [A-Za-z]/.test(node.text)&&!ts.isImportDeclaration(parent))text=node.text;
  }
  text=text.replace(/\s+/g,' ');
  if(text.length>1&&!seen.has(text)){
   seen.add(text);const unchanged=after.replace(/\s+/g,' ').includes(text);
   const advanced=/Provider|Resend API|Cron secret|Heartbeat|Scheduler|worker execution|server configuration|provider credentials|Activation timestamp|Workspace binding|Pending queue|Email worker/.test(text);
   const moved=file.endsWith('email-panel.tsx')&&['Provider','Configuration','Sender domain','Automatic sending setup','Attempts'].includes(text);
   const removed=/Desktop crop|Mobile crop|No original file-size limit|Large images are optimized|Required image|Loading dimensions|Template available|Focal position updates/.test(text);
   items.push({file,line:source.getLineAndCharacterOfPosition(node.getStart(source)).line+1,before:text,classification:removed?'REMOVE FROM OWNER UI':moved?'MOVE TO ADVANCED':unchanged?'KEEP':advanced?'MOVE TO ADVANCED':'SIMPLIFY',note:moved?'Moved out of the primary owner workflow into a closed support disclosure.':unchanged?(advanced?'Already in a closed Advanced disclosure; retained for support.':'Existing business label, instruction, status or safety information retained.'):'See corresponding implementation diff; payload values remain unchanged.'});
  }
  ts.forEachChild(node,visit);
 }
 visit(source);
}
for(const section of editableWebsiteSections)for(const field of section.fields){
 const next=ownerFieldLabel(field.label);
 items.push({file:'src/modules/content/website-schema.ts',line:0,before:`${section.id}: ${field.label}`,classification:field.kind==='image'?'SIMPLIFY':next!==field.label?'SIMPLIFY':'KEEP',note:field.kind==='image'?'Preview and Replace remain primary; redundant metadata removed. The previously advanced raw address remains in Technical details.':field.kind==='visibility'?'Already-hidden form value retained; owner-facing switch remains in the section header.':`Display: ${next}. Stored key: ${field.key}.`});
}
items.push(
 {file:'src/app/admin/website-editor.tsx',line:0,before:'Stored image filename and natural pixel dimensions',classification:'REMOVE FROM OWNER UI',note:'Preview retained; filename/dimension display removed.'},
 {file:'src/app/admin/bookings-panel.tsx',line:0,before:'Order UUID',classification:'MOVE TO ADVANCED',note:'Technical details disclosure. Booking reference remains primary.'},
 {file:'src/app/admin/bookings-panel.tsx',line:0,before:'Product UUID fallback',classification:'HIDE',note:'Product name, or Product unavailable.'},
 {file:'src/app/admin/bookings-panel.tsx',line:0,before:'Email attempt count and last error code',classification:'MOVE TO ADVANCED',note:'Technical details disclosure.'},
 {file:'src/app/admin/email-panel.tsx',line:0,before:'Sending attempt count',classification:'MOVE TO ADVANCED',note:'Technical details disclosure.'},
 {file:'src/app/admin/destinations-editor.tsx',line:0,before:'Latitude and longitude',classification:'MOVE TO ADVANCED',note:'Advanced: map position.'},
 {file:'src/app/admin/destinations-editor.tsx',line:0,before:'Destination page slug',classification:'MOVE TO ADVANCED',note:'Autogenerated value retained; Advanced: page address.'},
 {file:'src/app/admin/catalog-panel.tsx',line:0,before:'Existing product page slug',classification:'MOVE TO ADVANCED',note:'Advanced: page address.'},
 {file:'src/app/admin/product-name-fields.tsx',line:0,before:'New product page slug',classification:'MOVE TO ADVANCED',note:'Autogenerated value retained; Advanced: page address.'},
 ...['Destination main image address','Destination social image address','Reviewer photo address','Product social image address'].map(before=>({file:'src/app/admin/image-field.tsx',line:0,before,classification:'MOVE TO ADVANCED',note:'Primary image preview and Replace; original raw-address editing retained under Technical details.'})),
 {file:'src/app/admin/review-language.tsx',line:0,before:'Raw review language code',classification:'SIMPLIFY',note:'Common language names in the owner control; custom language codes retained under Advanced: other languages.'},
);
const counts=Object.fromEntries(['KEEP','SIMPLIFY','HIDE','MOVE TO ADVANCED','REMOVE FROM OWNER UI'].map(c=>[c,items.filter(i=>i.classification===c).length]));
writeFileSync('docs/ADMIN-SIMPLIFICATION-INVENTORY.json',JSON.stringify({basis:'HEAD before this change; source text occurrences deduplicated within each file, plus expanded editable CMS fields and explicit dynamic displays. Counts are inventory entries, not unique concepts or screenshots.',files:files.length,counts,total:items.length,items},null,2)+'\n');
console.log(JSON.stringify({files:files.length,total:items.length,counts}));
