// Presentation only: operational facts and transactional messages are not editable here.
const text = (key:string,label:string,initial:string) => ({key,label,initial,kind:'text' as const,max:700});
const seo = (prefix:string,title:string,description:string) => [text(`${prefix}.seoTitle`,'Search title',title),text(`${prefix}.seoDescription`,'Search description',description),{key:`${prefix}.seoImage`,label:'Social preview image',initial:'/images/lake.webp',kind:'image' as const,max:2000},text(`${prefix}.seoAlt`,'Social image description','Lake Shkodra')];
export const editorialSections = [
 {id:'homeRoute',title:'Homepage stop overview',fields:[text('homeRoute.eyebrow','Eyebrow','Route & stops'),text('homeRoute.title','Heading — use {count} for the published stop count','{count} stops around Shkodra'),text('homeRoute.text','Introduction','View the published boarding points on the route page.'),text('homeRoute.action','Route action label','View Route & Live Map')]},
 {id:'routePage',title:'Route & Live Map presentation',fields:[text('routePage.eyebrow','Eyebrow','Route & Live Map'),text('routePage.title','Heading','Where’s the van?'),text('routePage.text','Introduction','See the van live, find your stop and plan your next ride.'),text('routePage.departures','Departures heading','Next departures'),text('routePage.stops','Stop overview heading','Your route today'),text('routePage.mapAction','Map action label','Show on map'),...seo('routePage','Route & Live Map | Sightseeing Shkodra','Follow the van, find published stops and check scheduled departures.')]},
 {id:'editorialLabels',title:'Shared visitor action labels',fields:[text('labels.ticket','Ticket details link','View ticket details'),text('labels.faq','FAQ link','Questions? View FAQ'),text('labels.guide','Guide link','Read the guide'),text('labels.destination','Destination link','Explore destination'),text('labels.tour','Tour link','View the day tour'),text('labels.reviews','All reviews link','See all reviews on Google Maps'),text('labels.leaveReview','Leave review link','Leave a review'),text('labels.originalReview','Original review link','View original'),text('bookingDialog.title','Booking dialog heading','Book your day'),text('bookingDialog.text','Booking dialog introduction','Choose your day and passengers to check available departures.')]},
 {id:'bookSeo',title:'Booking search & social preview',fields:seo('bookPage','Book your day | Sightseeing Shkodra','Choose your date and passengers, check available departures and reserve your Sightseeing Shkodra ticket.')},
 {id:'faqSeo',title:'FAQ search & social preview',fields:seo('faqPage','Questions & answers | Sightseeing Shkodra','Answers about booking, boarding, ticket inclusions and live tracking.')},
 {id:'exploreSeo',title:'Explore search & social preview',fields:seo('explorePage','Explore Shkodra | Sightseeing Shkodra','Discover published visitor guides to Shkodra and its surroundings.')},
];
export const editorialDefaults = Object.fromEntries(editorialSections.flatMap(s=>s.fields).map(f=>[f.key,f.initial]));
export function routeHeading(template:string,count:number|undefined){return count ? template.replaceAll('{count}',String(count)).replace(count===1 ? /\bstops\b/ : /$^/,'stop') : template.replaceAll('{count}','Published');}
export const sectionConsumers:Record<string,string> = {
 hero:'Homepage',intro:'Homepage ticket section; Route ticket heading',homeRoute:'Homepage published-stop overview',route:'Tour and sample travel companion destination stories; visibility also affects homepage and Route stop overviews',routePage:'Route & Live Map (the map and operational warnings always remain available)',live:'Homepage and Tour live-map presentation',departures:'Homepage, Tour and Route timetable presentation',reviews:'Homepage guest reviews',notebook:'Homepage destination cards',final:'Public closing invitation, except FAQ, Booking and booking-management pages',navigation:'Desktop and mobile public navigation',footer:'Public footer business/contact information; does not rename the application',editorialLabels:'Shared public actions and booking dialog',bookSeo:'Booking search/social metadata',faqSeo:'FAQ search/social metadata',exploreSeo:'Explore search/social metadata',faq:'FAQ page',tourPage:'Tour; inclusions heading also used by homepage ticket',explorePage:'Explore',bookPage:'Booking',dayPage:'Sample travel companion only',seo:'Homepage search/social metadata',whatsapp:'Public contact button',legalprivacy:'Privacy Policy',legalterms:'Terms & Conditions',
};
